FROM node:20.12.2-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

COPY ./public /app/public
COPY ./src /app/src

ENTRYPOINT ["npm", "start"]