services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pwd
    volumes:
      - ./postgres/db:/var/lib/postgresql/data

  backend:
    build:
      context: Backend/TestProject
      dockerfile: Dockerfile
    env_file: Backend/TestProject/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build:
      context: Frontend
      dockerfile: DockerFile
    ports: 
      - "3000:3000"
    depends_on: 
      - db
      - backend